server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name:app}

spring:
  application:
    name: notification

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

rabbitmq:
  management:
    base-url: http://localhost:15672
    username: rabbitmq
    password: rabbitmq
    vhost: /
    poll-interval: 10000
