server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name:app}

spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5435/orders
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migrationinventory:
  base-url: http://localhost:8082